# Generated by Django 3.2.13 on 2023-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0041_auto_20231113_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='level3_pain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='level3_power',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='level3_push',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
