# Generated by Django 3.2.13 on 2023-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0044_auto_20231125_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file_paths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
