# Generated by Django 3.2.13 on 2023-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0045_userprofile_file_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file_paths',
            field=models.JSONField(default=dict),
        ),
    ]
