# Generated by Django 3.2.13 on 2023-12-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0046_alter_userprofile_file_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Level1 Option'},
        ),
        migrations.AlterModelOptions(
            name='bucket',
            options={'verbose_name': 'Level1 Bucket'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Level1 Question'},
        ),
    ]
