# Generated by Django 3.2.13 on 2024-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0047_auto_20231214_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file_paths',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
