# Generated by Django 3.2.13 on 2024-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0048_alter_userprofile_file_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
