# Generated by Django 3.2.13 on 2023-12-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimenealUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('client_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_admin_user', to=settings.AUTH_USER_MODEL)),
                ('client_subadmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_subadmin_user', to=settings.AUTH_USER_MODEL)),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limeneal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
