# Generated by Django 3.2.13 on 2023-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limenealuser',
            name='user_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
