# Generated by Django 3.2.13 on 2023-12-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0002_limenealuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limenealuser',
            name='super_admin',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
