# Generated by Django 3.2.13 on 2023-12-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0004_auto_20231214_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limenealuser',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='limenealuser',
            name='client_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'clientadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='limenealuser',
            name='client_subadmin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'clientsubadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_subadmin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
