# Generated by Django 3.2.13 on 2023-12-15 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0005_auto_20231214_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('C2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('C3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('T1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('T2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
