# Generated by Django 3.2.13 on 2023-12-15 19:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0007_auto_20231215_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlist',
            old_name='C1',
            new_name='lp1',
        ),
        migrations.RenameField(
            model_name='adminlist',
            old_name='C2',
            new_name='lp2',
        ),
        migrations.RenameField(
            model_name='adminlist',
            old_name='C3',
            new_name='lp3',
        ),
        migrations.RenameField(
            model_name='adminlist',
            old_name='T1',
            new_name='ltb',
        ),
        migrations.RenameField(
            model_name='adminlist',
            old_name='T2',
            new_name='ltf',
        ),
        migrations.AddField(
            model_name='adminlist',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='admin_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='admin_contact_details',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='admin_designation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='admin_email_id',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='admin_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='creating_assessee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='employment_status',
            field=models.CharField(choices=[('Full-Time Employee', 'Full-Time Employee'), ('Part-Time Employee', 'Part-Time Employee'), ('Full-Time Contract', 'Full-Time Contract'), ('Part-Time Contract', 'Part-Time Contract'), ('Temporary', 'Temporary')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='gst_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='org_client_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='pan_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='rights_given',
            field=models.CharField(choices=[('Admin Access', 'Admin Access'), ('Sub-Admin Access', 'Sub-Admin Access'), ('Client Admin Access', 'Client Admin Access'), ('Client Sub-admin Access', 'Client Sub-admin Access'), ('End-User Access', 'End-User Access')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='total_tools_given',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='type_of_business',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminlist',
            name='uid',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
