# Generated by Django 3.2.13 on 2023-12-24 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0009_auto_20231224_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_admin_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
