# Generated by Django 3.2.13 on 2024-01-06 20:27

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0011_auto_20231231_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlist',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2024, 1, 6)),
        ),
        migrations.AlterField(
            model_name='clientadminlist',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2024, 1, 6)),
        ),
        migrations.CreateModel(
            name='ClientSubAdminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(default=datetime.date(2024, 1, 6))),
                ('org_client_name', models.CharField(default='', max_length=255)),
                ('address', models.TextField(default='')),
                ('type_of_business', models.CharField(default='', max_length=255)),
                ('pan_no', models.CharField(default='', max_length=20)),
                ('gst_no', models.CharField(default='', max_length=20)),
                ('uid', models.CharField(default='', max_length=20, unique=True)),
                ('admin_name', models.CharField(default='', max_length=255)),
                ('admin_designation', models.CharField(default='', max_length=255)),
                ('employment_status', models.CharField(choices=[('Full-Time Employee', 'Full-Time Employee'), ('Part-Time Employee', 'Part-Time Employee'), ('Full-Time Contract', 'Full-Time Contract'), ('Part-Time Contract', 'Part-Time Contract'), ('Temporary', 'Temporary')], default='', max_length=20)),
                ('admin_contact_details', models.CharField(default='', max_length=20)),
                ('admin_address', models.TextField(default='')),
                ('admin_email_id', models.EmailField(default='', max_length=254)),
                ('lp1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lp2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lp3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ltb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ltf', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_clientsubadmin_lists', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientsubadmin_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
