# Generated by Django 3.2.13 on 2023-12-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('clientadmin', 'Client Admin'), ('clientsubadmin', 'Client Sub-Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
